### ISSUE TITLE
Cannot Resolve or Find Documentation

### ISSUE THREAD

**Issue by Geefbird** [taburineagle/NeewerLite-Python#83]
Exception has occurred: OSError
[WinError -2147020577] The device is not ready for use
  File "G:\Programs\NEEWER LITE\NeewerLite-Python.py", line 2139, in findDevices
    devices = await BleakScanner.discover() # scan all available Bluetooth devices nearby
  File "G:\Programs\NEEWER LITE\NeewerLite-Python.py", line 2600, in workerThread
    threadAction = _loop.run_until_complete(findDevices()) # add new lights to the main array
OSError: [WinError -2147020577] The device is not ready for use

Turns out I didn't have Bluetooth on lol, so yea, I am an idiot... 

Now I am just trying to get it to see my lights when I scan but so far no luck.

**Comment by taburineagle** [comment]
Hi @Geefbird!  Interesting... looking through the old versions of your post, it looks like you're using Windows.  Can you see any of the unpaired Neewer lights in Windows' Bluetooth and Other devices control panel?  If Windows can't see the lights, then NeewerLite-Python isn't going to be able to either.

**Comment by Geefbird** [comment]
I don't know that the BH-30S lights work with Bluetooth but they are listed in the documentation for this. I didn't check to see if windows can see them, but I will do that. I was under the impression that using the http server would connect to the lights using WiFi and that is what I was trying to do.

**Comment by taburineagle** [comment]
Got you - although those other 15 comments help me to understand the problem better 🤣  Yeah, Neewer lights (except for a few of them that have a proprietary remote) don't use WiFi, the ones that communicate with the official Neewer app all use Bluetooth in one way or another, and those are the ones that NeewerLite-Python are written to work with.  Your PC also needs to be able to use BLE (Bluetooth Low-Energy) devices, which most computers _should_ be able to, although that's down to the Bluetooth chip on your motherboard or the Bluetooth dongle you use.  How do you have Bluetooth set up on your PC?

Also, [there is documentation for NeewerLite-Python](https://github.com/taburineagle/NeewerLite-Python/wiki), although I do admit, I need to update it _badly_

**Comment by Geefbird** [comment]
I just use the bluetooth chip in the MoBo but maybe that doesn't handle BLE so I might have to order one of these Neewer dongles for 20 dollars and give that a shot. 

All personal issues aside thank you so much for writing this and putting together/out there for everyone I have wanted to do this for a really long time and have just never been able to sit down and give it an honest effortf. Plus my coding skills in general let alone in python are not great lol so something of this extent would take me months. Sincerely appreciative.

**Comment by taburineagle** [comment]
You're welcome, thanks for saying so!  I've written several programs in other languages, but this project is actually my first grand-scale Python project actually, so I know what you mean 😊  [This is the Bluetooth dongle I use](https://www.amazon.com/gp/product/B07V1SZCY6/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1), which is around $9 at Amazon and works pretty decently with the Neewer lights - or at least I've found it to work pretty well!

**Comment by Geefbird** [comment]
Wish I would have seen that before I ordered mine directly from NEEWER lol. It will be here tomorrow and then I will let you know how everything worked out and whether or not I was able to see my lights and get them set up. I really hope it works. This will be a total game changer for my lighting and stream immersion.

**Comment by taburineagle** [comment]
Ah, ha, timing is everything 😅  I hope it works too!  I don't know if the Neewer dongles work with Bluetooth in general, or just a proprietary app that they use, but if it doesn't, I can definitely vouch for the TP-Link one.

**Comment by Geefbird** [comment]
the level of sadness that will be had if this one doesn't work is indescribeable lol

**Comment by taburineagle** [comment]
I know what you mean 😐  It wasn't [this one](https://neewer.com/products/neewer-2-4g-usb-wireless-transmitter-adapter-66600862), was it?  That one doesn't do Bluetooth (it's for specific lights that use 2.5G control, but not Bluetooth... I _think_, I've not used one myself, so I'm not 100% sure on that one...)

**Comment by Geefbird** [comment]
Yea I think that is the one and now I am confused... and probably going to be very upset. That was the only dongle I found on NEEWER's site.
I have been waiting 8 days for this stupid thing. Now I just want to cancel it

**Comment by Geefbird** [comment]
Well just to be safe I ordered the one you linked as well and it will be here today so if the one I got from NEEWER doesn't work then I have this one.

**Comment by Geefbird** [comment]
I am trying to install the driver for the TP-Link dongle and it says it fails and asks if I have access to a Sys32 En-Us folder... which I am currently in right now but I keep hitting retry and it just keeps failing
How did you get this driver installed lol

**Comment by Geefbird** [comment]
Ok so I got the driver to install, the dongle is set up my lights are turned on, I know they support bluetooth because they have infinity mode and are in infinity mode (which is NEEWER's Bluetooth) but it isn't finding my lights in the app, in the http server, or on the PC through the dongle. They are BH-30S lights so they should work. I can control them through bluetooth with my phone. 

Appreciate any and all help, I am so worn out and frustrated lol

**Comment by Geefbird** [comment]
and when I run script I get OSError: WinError -2147020577 The device is not ready for use

**Comment by Geefbird** [comment]
and then to top off all of the annoying, frustrating, time wasting bits of the day as it turns out my motherboard does in fact support bluetooth low energy. So now I am extremely confused as to why I can't find these lights on my PC.

**Comment by taburineagle** [comment]
Hmm, so am I - I actually didn't need to install any drivers to get the dongle to work, it just showed up on my system.  I'm not sure which version of Windows you're using, but it did auto-install on Windows 10.  I'm curious why _nothing_ is showing the light though, at the bare minimum, Windows itself should be seeing it - if you go to the Windows Bluetooth control panel (in Windows 10, it's `Settings > Devices > Bluetooth & other devices > Add Bluetooth or other device > Bluetooth`), does the light show up there?  My lights do show up in that list (as well as a printer and a TV that isn't mine...)

![image](https://github.com/taburineagle/NeewerLite-Python/assets/18430526/9166dee2-980a-4108-96b7-ce801774a701)

**Comment by taburineagle** [comment]
Also, are you using the last version of NeewerLite-Python, or the one that's currently the main commit?  If Windows can see the light, but NeewerLite-Python can't, the older version (0.12) didn't have Infinity support - the new version I will be releasing soon (as well as the current main commit) _do_ have Infinity support.

**Comment by taburineagle** [comment]
Also (ha, multiple posts), you might already know this, but if the light is still connected to your phone's Neewer app (even if the program isn't currently loaded, but the light is still linked to it), nothing else will be able to access it, so that could also be an issue.  You'd need to quit the Neewer app for the light to show up and be pairable on other devices.

**Comment by Geefbird** [comment]
Ok, so if the NW-2022 blah blah blah (lol) is a NEEWER light, then yes my computer is and has been seeing the lights, but the Python has never. I am going to replace the Python code with the codes in those two links. They don't actually go to a downloed but rather a text file so I will just copy and paste them and then run it. Maybe it was the lack of infinity support... I am hoping because I really want this to work lol. So so bad.

**Comment by Geefbird** [comment]
OMG OMG OMG OMG OMG!!! The change in the Python code to support Infinity totally fixed it! It found my lights immediately and linked them without issue! I am going to geek out now and try to get all of this stuff set up to work with StreamerBot and StreamDeck controlling them. Thank you so much! I don't even care that I wasted 30 dollars on dongles now lol. I am sure I can return them, or at least the one to Amazon.

**Comment by Geefbird** [comment]
Sooooooo lol, I feel terrible asking so many questions and feel like a huge pain in the ass... but I am trying to trigger the lights using the HTTP server Daemon, and it worked for the first request to turn on the light, but now when I try to trigger a second action to turn off the light or turn on the other light it says that the "Server requested an action, but we are already working on one. Please wait" and no matter how long I wait it just keeps saying that. Not sure what is going wrong or how to fix it.

**Comment by taburineagle** [comment]
Ahh!  I'm glad you got it to work - I assumed you had the latest commit already, that's why I was confused why the lights weren't detecting.  Yeah, I am very close to releasing a new version with all of that support baked in to it, but I have to test and troubleshoot _all_ of the functionality to make sure it works perfectly before then, and the HTTP server is one that I admit I haven't fully put through its paces yet with all of the Infinity changes.  Apologies for the growing pains, I _will_ try to check into that ASAP, because I'm getting the same result here.  I might not have a chance to really get into it though until the weekend, but I will let you know how it's going when I have a moment to!

**Comment by Geefbird** [comment]
Yea no rush I can't imagine how long it takes to fully go through all of it and make sure all of the parts function properly. Looking forward to it with great excitement lol. I can try to figure out why it is breaking when an HTTP request is sent. I feel like it is continuing the request infinitely even once it is completed, processing it over and over without realizing it was successful or even if it fails, but I don't know for sure. I am just thankful for the code, the support, and as soon as it is working I am going to go nuts with this lol. Might even have to make a YouTube video about how amazing it is. Being able to have my wireless lights set up and turn them off from the UI is amazing as is, but when I can do all of the other stuff I have planned like triggering color changes, brightness, on/off, FX etc. with stream events, my heart rate and viewer interactions... yea, it's going to be a great day lol. 

Thanks again for everything and best wishes on all of the checks and balances, I hope it doesn't take too much effort or cause nearly as much frustration as just trying to see the lights caused me lol.

**Comment by taburineagle** [comment]
You're welcome!  I'm hoping you can get all of those things set up, it sounds like you have an awesome set up in mind!  I actually might already have sorted the problem.  I fixed one small error in the command processor for the HTTP server (I used the wrong variable name in one small section), and that _should_ help the `"The HTTP Server requested an action, but we're already working on one.  Please wait..."` error.  Check the latest commit out and see if that resolves that - [right click and choose to save the file for the NeewerLite-Python.py file](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/main/NeewerLite-Python.py).  The ui_NeewerLightUI.py file hasn't changed, so you don't need to re-download that one.

**Comment by Geefbird** [comment]
I resolved that error but then there was another regarding python.lock, and then I ran the HTTP server and upon request it triggered the first, then said entering send mode or something and wouldn't let me send anymore requests.

**Comment by taburineagle** [comment]
_Hmm_ - well, the winrt part of the program is only to solve a very old Windows error that would show up when launching the program on older versions of Windows that used _winrt as a Python library (Windows 7 basically), and the way I wrote the program, should not show that error (basically, what happens is - if the module exists, it does something that tells Windows that it's fine, and if it doesn't exist, it just goes past that part), so I'm _not_ really sure why that showed up... because I didn't change anything with that section in that last edit, and honestly can just cut that section out completely on later Windows versions.

The python.lock error is usually when the program quits out, but when you go to start it up again, a lock file exists, as it didn't close properly the time before (I did this so that you could only run one instance of the program at a time, as only one instance can link to the lights at a time) - the best way to get around that is to use --force_instance on the command-line when launching the HTTP server.

Ha, still getting to the finish line... still getting there 🤣  The last version (the 0.12d one you were using before) is more or less rock-solid, although as you know, it's not Infinity-ready, so the latest commit is the best way to go at the moment.

**Comment by Geefbird** [comment]
Yea I just worked around it by changing it to winsdk since that works with more recent Python, and I am using 3.10
I no longer get that error as the library is current and working. I still get the another instance error but have just been deleting the file from appdata to move along with checking errors rather than forcing the instance and ignoring them. Once past the instance lock error I recieve 

no running event loop
  File "G:\Programs\NeewerLite-Python\NeewerLite-Python.py", line 1787, in setUpAsyncio
    asyncioEventLoop = asyncio.get_running_loop()
  File "G:\Programs\NeewerLite-Python\NeewerLite-Python.py", line 3791, in <module>
    setUpAsyncio() # set up the asyncio loop
RuntimeError: no running event loop

I did take a screenshot of the terminal in a forced instance and what it is outputting when I send a command and then try to send another.
![TeminalPythonNEEWER](https://github.com/taburineagle/NeewerLite-Python/assets/130674516/0a9c9f2e-14b8-4049-9bf3-d77644409cee)

**Comment by taburineagle** [comment]
_Hmmmm!_  That's even more interesting - setUpAsyncio() is supposed to check for the running loop, and if it's not there, it creates it.  So technically the `RuntimeError` is correct, but it's because of that exception that that function creates the loop directly afterwards.  Also, NeewerLite-Python doesn't really need winrt _or_ winsdk, that library is only imported for one very specific error with old versions of Windows (it used to complain something along the lines of "apartment was not disconnected", but everything would work completely fine), and I could probably just remove that entire section at this point with no issues at all, as that's literally its only function in my program.

How exactly are you running NeewerLite-Python, if you don't mind me asking?  It sounds like you have it going through an IDE - or have a more stringent exception checker running (which is fine, I'm just curious where the errors are coming from, as both the _winrt and RuntimeError during setUpAsyncio() are _correct_, but in standard runtime, they're both handled in the script after those exceptions are thrown, so the Python interpreter is just saying "something's happening here, let's hope we have it handled"...)  My usual runtime is Visual Studio Code, but I don't have as stringent an exception catcher running.

Also, I see the last 2 URLs have `%0A` at the end of the address, which might also be adding to the issue of it not sending...  It looks like you sent `FA:06:FE:66:87:41` an on command, then `CA:6F:17:4F:01:61` an off command twice, then sent `FA:06:FE:66:87:41` another on command (but with that extra %0A at the end of the URL).

**Comment by Geefbird** [comment]
I am using VSC to run the scripts. Only program I like and am familiar with. Also realized I had raised exceptions ticked after you said that bit about you not having an exception catcher running so that is my fault lol, I am no longer getting the Asyncio error. Stupid me lol, I didn't even realize I had that on... I don't think I did originally and must have ticked it by accident or on purpose for some reason and forgot to turn it off.

Also I am seeing that when I use the UI to send commands after eash command it enters Send Mode, and then instantly leaves Send Mode allowing for another command. Where as when using the HTTP it never leaves send mode after entering it.

**Comment by taburineagle** [comment]
**Ahhhh**, got you - that makes a lot more sense 😅  I was going to say "why are they getting so many errors?", but then noticed what the errors _were_ and went "ah, they must have 'Raised Exceptions' turned on" - VSC should be fine for running it, I usually do use that for debugging it, but try to use the normal Windows/Mac OS/Linux console to run it for normal testing.  Try using the Windows console with HTTP mode if you get a chance, and see if running it that way changes anything.  Shift-Right Click on the window you have NeewerLite-Python in, choose "Open PowerShell window here", then when that opens, type "cmd" and enter, and then either

`python NeewerLite-Python.py --http`
or
`python3 NeewerLite-Python.py --http`

If you are using VSC, how are you triggering HTTP daemon mode then?  "Python File With Arguments"?

Interesting on the GUI and HTTP difference on send mode - the Terminal window you shared above _does_ show it entering and exiting send mode several times, but you're saying that it doesn't actually exit send mode through the HTTP daemon.  I'll have to check into that a bit more on my end - when I did that one tweak yesterday morning and tested it out, the HTTP server was exiting send mode correctly after every command.

**Comment by taburineagle** [comment]
OK, I just tested it here with a CL124 (which is not an Infinity light) and a SL90 Pro (which is an Infinity light) and the HTTP server turned the SL-90 off, on, off and then on again without issues here - 

![image](https://github.com/taburineagle/NeewerLite-Python/assets/18430526/35b1bffe-d11d-4a87-a377-9d2e57b889b6)

**Comment by Geefbird** [comment]
I am using VSC with arguments to launch HTTP. I am going to try using the regular console right now though and see if I can get better results. I just got off of work so I don't know how long I will be aawake, but if it works I might be up all night lol. Here is to hoping for great results.

**Comment by Geefbird** [comment]
Ok running with PowerShell still has the same issue. I guess what I was seeing with the UI is that it actually says "Going into send mode" and "Leaving send mode" while using HTTP does not say "Leaving send mode" so I assumed that it was not. If that is not the issue I don't know what it might be, and if it is working for you I am even more lost because nothing I do after the first request works.

**Comment by taburineagle** [comment]
Got you, got you - and I definitely got you in the tired department!  I see, in the end of writeToLight(), which is the function that communicates with the lights, I wrote the return back to the main thread to say the phrase "Leaving send mode and returning to background thread" is only written to display when using the GUI, so that's why you're not seeing it in HTTP mode.  I can change this.

OK, let's start from the beginning here - try deleting the `light_prefs` and `__pycache__` folders in the NeewerLite-Python folder if they exist, re-download the .py files from the latest commit and let me know the order of operations of exactly what you're trying to accomplish, maybe there's some odd combination of things I'm not seeing on my end because I'm not aware of what to look for.  I wonder if the issue could be that I've not tried it out with 2 Infinity lights at once in HTTP mode (it looks like in your Terminal window you have 2 BH-30s?)  But you do say the GUI acts as it should, but the HTTP server is being finicky...  One other thing to be aware of, if you try to send a command to one light, but are trying to still link to 2 lights, there might be an issue there too.

**Comment by Geefbird** [comment]
Ok I deleted the two folders, re-downloaded the files, run the NeewerLite-Python.py using PowerShell instead of VSC, wait for it to say that both lights are linked, turn off the first light and then attempt to turn off the second light a few seconds later but nothing happens. I also tried to trigger both lights to turn on or off at the same time and that didn't work, it only turned off one. I did not taake a screenshot of the terminal on that one as it presented no different information than this screenshot. 
![TeminalPythonNEEWER](https://github.com/taburineagle/NeewerLite-Python/assets/130674516/f6973cba-d063-45f5-a6a6-a9a5de49c558)

**Comment by Geefbird** [comment]
Ok so I finally had a moment to try those out and I am not sure why but using light =1 and light =2 executes every request with no hang up. So for some reason using the lights actual mac address is what is causing the problem. I have successfully executed 6 requests using their numerical value instead of mac address with no issue.
I am going to keep testing and see if I run into any other issue but I have to say I think you figured out my issue or at least a way around it.

**Comment by Geefbird** [comment]
So now I have a question, if I wanted to perform a request to turn both lights on how would I write that out? 
I tried what I assumed would work but it did not.

**Comment by taburineagle** [comment]
Ah, excellent!  That gives me something to check on, as Infinity lights use the MAC address in their commands to actually communicate with the light, so maybe something is getting jumbled there.  Semicolons are how you do multiple lights at once - so it'd be something like:

`http://127.0.0.1:8080/NeewerLite-Python/doAction?light=0;1&off`

**Comment by Geefbird** [comment]
yea I got the multiples thing from the documentation. I had missed it the first time looking through it but read through it all again and got everything working. SO! It all works now, I have run a battery of tests and as long as I am using their numerical assignments versus their MAC addresses everything is flawless. Working with multiple applications, requests, and functions. Amazing. Thank you so much for going down this rabbit hole with me and getting it all sorted out. If you need any future testing on anything just let me know and I would be happy to return the favors. Appreciate all of the effort a great deal.

**Comment by Geefbird** [comment]
Ok I am bacak with another edition of I suck lol. I cannot for the life of me figure out how to get scenes to work. I have tried using SCENE and ANM and it for some reason is just changing my lights to about 5000K and 50% brightness. If you have any thoughts or an example of something that you have used and works I would appreciate it a lot because I have been at this for an hour almost trying different things.

**Comment by Geefbird** [comment]
and now the webserver won't even find my lights lol, but the UI still sees them. I am too tired to keep messing with this right now, and I need to go to work in an hour. Hopefully I can get this figured out.

**Comment by taburineagle** [comment]
Ha, it's cool @Geefbird - I'm glad that the light ID #s work with the HTTP server!  I need to take a look at the MAC address system, as specifying a MAC address is just supposed to return a light ID# in the first place... but apparently something's not happy with that at the moment.

As far as the SCENES... ha, _no, that edition of suck belongs to me_ - like I mentioned in the past, I do the GUI stuff first, and then the CLI and HTTP stuff - and Infinity FX are drastically different than the normal light FX, so that section needed a complete re-write.  The FX work with the GUI, but I need to work on the CLI/HTTP subsystem to bring it in line with the GUI system.  As the backbone of that system is in place, it shouldn't take a lot of extra work to bring all of that to the CLI/HTTP part of the program -- but it's not there yet... that's one of the reasons I haven't released the next version yet 😶

**Comment by Geefbird** [comment]
lol that edition of suck, I would like to steal that saying. That is too good. As much as I am sorry that it isn't there yet I am glad to know that it wasn't me just making mistakes and being dumb. I am sure you will reach your target soon enough you've gotten a lot done and though I know there is a lot more to do it might just flow out of you effortlessly and you be surprised how fast you got it all done. Maybe... lol

As for the scenes/animations Infinity light situation I found a temporary solution for me. Since everything else works I don't need my presets for anything and can set all of those up for the FX scenes and just use the http server to trigger those. Is it a perfect solution? No. It is however good enough and works just fine. Best of luck with all of the work ahead, I am sure I will be back with more questions at some point, and again, feel free to reach out with any testing requests if you need to since I have 2 infinity lights and that is something you are currently working on.

**Comment by taburineagle** [comment]
Hehe, I should just make that "edition of suck" thing my tagline 😁  I'm glad you have a method sorted out for the FX, even though it's not 100% ideal!  I will definitely take a look at that ASAP - there are a lot of changes currently underway at work, so I might be in and out the next few weeks, but I will keep forging ahead as I can - I know what needs to be done with that at least, so I have a good starting point to get it implemented.

**Comment by Geefbird** [comment]
I am trying to help a member of my Twitch community set this up and he has a Gl1C and when he tries to control anything other than HSI through either the GUI or HTTP it doesn't work. GUI doesn't push any information on it to the console, and through HTTP it pushes this error, but when trying to trigger a preset it says "going into send mode" and then nothing after that.
![image](https://github.com/taburineagle/NeewerLite-Python/assets/130674516/dc60f09f-83ca-45ac-b74e-66746152d74f)

**Comment by taburineagle** [comment]
2 things for this one -
- The Infinity protocol is a new one, and I need to add lights to the list of available Infinity lights as they pop up, so that _might_ be one of those - I'm going to have to check a bit later on, I just got up (3rd shift woes)
- They're using an old version (2024-02-15-RC) - the latest commit (which I should have changed the date of when I commited it, but I - ugh - _forgot_) is **2024-03-02-RC**  That "list index out of range" issue was fixed in this commit a few days ago -

![image](https://github.com/taburineagle/NeewerLite-Python/assets/18430526/cfb27de4-4fe5-4f95-b1c7-00ccd1fb9679)

**Comment by Geefbird** [comment]
OOF 3rd shift.. I actually work overnights too lol

And yeaaaaa.... we just noticed that he wasa using old code and I came to tell you that when I saw your response lol

**Comment by taburineagle** [comment]
Ha, yes!  **_Night work!_**  It's... not for everyone 🤣  Yeah, I have a list of lights in the program with their specs, the color temp ranges, if they're CCT only lights (some Bi-color lights can only do CCT mode, which is _another_ protocol), if they're Infinity lights, etc.  And I filled the information out as well as I have access to documentation, but I don't have the lights in front of me, so I can't accurately know how every light is going to work on the program, that's why it helps to hear from people that have specific lights like that to know how they run...

![image](https://github.com/taburineagle/NeewerLite-Python/assets/18430526/d406001c-4635-46b4-ac05-49540a1d0a11)

Looking up the GL1C, it actually looks like _that's one of the lights that supports that Neewer dongle you got last week_ - but it also supports Bluetooth, which means NeewerLite-Python should theoretically be able to control it.  I'm not sure if it's Infinity though, I'm looking for that... it looks like (according to Neewer's website) it might be one of those "Infinity protocol, but not Infinity standard" lights, which I just added support for recently.

**Comment by taburineagle** [comment]
And as I look at the table above, I don't even have the GL1C listed, so I can add that one in too, and _hopefully_ it uses a compatible protocol...

**Comment by taburineagle** [comment]
OK, I added a new commit - I rewrote the MAC address procedure (which _hopefully_ will work now, but I still think it needs more finesse) and added the GL1C to the database.

**Comment by Geefbird** [comment]
The lights he has have CCT, HSI, and SCENE modes. So far using the UI and http server he was able to get CCT and HSI working but not scenes. Through neither the GUI nor the http server. He wasn't originally able to use presets either but I had him write "light=1&use_preset" and that got presets to work with his light as well. I had him update to the most recent commit and there was no change, at least in the GUI, the http server however wasn't responding to any requests at all. Looks like it never went into send mode, but I could be wrong because that happens a lot lol. I attached a screenshot of his console when trying to use the server with the most recent commit but it doesn't provide much information. 
![image](https://github.com/taburineagle/NeewerLite-Python/assets/130674516/a725dac0-0b1e-41b4-acc7-e38c46a526b5)
Also, I was going to mention that you can add the BH-30S lights to the list of fully tested if you want as I have fully tested them with the GUI and http server and have everything working with them including external applications like StreamDeck, Touch Portal, StreamerBot. 1 light down.... 432948723965 to go lol.

**Comment by Geefbird** [comment]
although thinking about it now... maybe they aren't fully tested because scenes didn't work without using presets lol. I think that might be a bit of an endeavor though since each scene has different controls.

**Comment by taburineagle** [comment]
Ha, lol 🤣 "432948723965 to go" - I'm not sure if battery information is one of the parameters that get sent through BLE - I know channel and power status do, I'm going to have to check on that... I do know (or at least I think I remember seeing it) that the Neewer app itself does show battery status, so it might be possible.  DadBodNerd got in touch with me and said the latest commit I pushed works with the HTTP server, but the scenes still don't work, which is... a little confusing, but not a show stopper.

I also pushed a commit that _hopefully_ fixes the MAC address issue with the HTTP server - give it a try and see if that works now, when you get a chance.

**Comment by Geefbird** [comment]
Sorry for the late response, someone at work has been out all week so I have been extra tired all week lol. I am glad he got in touch with you directly, I think that is the best way to make any issues known and gives you the best opportunity to look into and fix things. As for the latest commit I did get a chance to test it and the MAC address issue is resolved. Requests can now be sent with either the assigned number or MAC address of the light without issue. Hell yea man!

**Comment by taburineagle** [comment]
Ha, I _love_ the new title 🤣  I'm going through a very similar thing at work, one of my coworkers' last days was on Friday, so I'm now the only one on my shift... ha, and it's pretty busy!  I'm glad to hear the MAC address change worked out for you!  I have SCENES in progress for the HTML server, and I sorted DadBodNerd out to the level you're at now (the program was seeing a similarly named light but not the one he's using, and it used the parameters for that light instead, that was his issue.)  More to come... hopefully soon!

**Comment by taburineagle** [comment]
Ha, oh, I'll push it --

**Comment by taburineagle** [comment]
^^ I'll push it _real_ good 😄  You're welcome!  Well, work is going well - it's a lot busier with one less person, but it's not quite exhausting yet...  I've never really felt like I slept well, so I definitely know what you mean there!  OK, with this latest commit (I pushed it to a separate branch for testing for now, but the functionality should be there), it _should_ add all Infinity FX functionality.  It also adds parameters for effects that support them, such as `bright_min`, `bright_max`, `temp_min`, `temp_max`, `hue_min`, `hue_max`, `speed`, `sparks`, and `specialOptions` (that one's mainly for effects like "Cop Car" that have several different options for how the colors work).

**Comment by Geefbird** [comment]
Pah puh puh push it... I see what you did there lol

**Comment by taburineagle** [comment]
Ha, yeah, dad-joke territory, but I had to go there 😅

**Comment by taburineagle** [comment]
Just let me know when you get a chance to test that out @Geefbird - everything should be good to go on the HTTP end...

**Comment by Geefbird** [comment]
ok I grabbed the files and will try to get it tested tomorrow. Been extra busy lately so I haven't had time yet but tomorrow is my day off and as of right now my day is wide open so hopefully I can get to that somewhat early on in the day. I will let you know once I do

**Comment by Geefbird** [comment]
ok I have tried the newest script but am running into an issue straight away. Firstly I don't know how to properly type out the requests to select specific scenes i.e. light=1;2&mode=scene ??? I don't know where to go from there. I have tried scene1 scene=1 and both seem to do nothing. 

The actual issue though is that when I choose to default to 1 by just using scene with no specific number it triggers only one light and not the other.

**Comment by taburineagle** [comment]
Hmm, I'm not sure on the one light not triggering, but yeah, something along the lines of:

`http://127.0.0.1:8080/NeewerLite-Python/doAction?light=1&mode=SCENE&scene=12`

Also, if you want to access all lights, you can use an asterisk instead of doing `1,2`

`http://127.0.0.1:8080/NeewerLite-Python/doAction?light=*&mode=SCENE&scene=12`

**Comment by Geefbird** [comment]
ahhhh I see where I was going wrong lol, I wasn't doing it right. 

In all seriousness though thank you for that asterisk tip, I will give that a shot in a bit. Just got off of work and am going to make some food, eat, and then test this out. See if U can get both to trigger a scene when using an asterisk.

**Comment by Geefbird** [comment]
Ok the asterisk thing works and causes both  lights to enter scenes with no issue, however I am still trying to work out controlling each scene and if I mess up anything it bricks the lights and they just pulsate white lol. I have to shut down the server, power off the lights and then start over. Which isn't really an issue once I get these scene settings figured out. Safe to say this commit works great, nothing seems to be having issues. Well except me... I am having issues lol

**Comment by Geefbird** [comment]
lol I just realized I have 2 NEEWER T100 bulbs for photography and those also work with this. I just tested them. They run into some issues after a bit but I will save that for another day since they aren't important right now.

**Comment by taburineagle** [comment]
Hello!  Ha, it's been a _busy_ last two weeks, so sorry for the late reply...  Ah, glad you got that sorted out!  I don't think the lights themselves are bricked, I think what's happening is the HTTP server sends one request that it doesn't know how to recover from, and then the program gets confused.  I need to be able to have it recover more gracefully from issues like that.  I actually wasn't aware that the T100C worked with NeewerLite-Python!  I've actually not heard of those, honestly, so the program is probably loading the default settings for those when it loads them in, which aren't technically correct (the default params are for "normal" old-style lights, and it looks like those are similar to the GL1C in capabilities), so I'll add that one to the list when I get a chance.

Do the T100Cs work with SCENE mode?  That's one dead giveaway that the params aren't 100% correct.

**Comment by Geefbird** [comment]
Honestly I didn't play with them enough to know if they even have a scene mode. I am going to pull them out again at some point and link them to the app on my phone to see exactly what paramaters they have and I will get back to you about them.

**Comment by Geefbird** [comment]
Yo! Lol long time no talk! I have a question because I am going out of my mind over here. For the last sseveral months since we got this all ironed out my lights have never failed or had an issue but just the other week they stopped working with the http server and I cannot get them to stay linked to it. I can open and use the GUI and link them and they will stay linked but once I connect them to the http they unlink and will not link. In the terminal it says link successful on both lights but no commands go through and when I open the browser page it says not linked for both lights...

If you have any idea what could cause this I would really appreciate the help because I have been trying everything for a week and gotten nowhere.

**Comment by Geefbird** [comment]
wouldn't you know it as soon as I ask for help I get them to start working again... wth lol

**Comment by Geefbird** [comment]
Yea... it keeps doing the same stuff again. The light links and then it immediately unlinks. I have no idea what started to cause this but it is quite frustrating.

**Comment by taburineagle** [comment]
_Hmm_, that's quite odd!  Sorry for the delay, I saw the initial post that the problem sorted itself, but missed the followup... that is so weird!  I haven't changed anything operationally, so stuff shouldn't just stop working like that - not trying to pass the buck, but possibly a system update or something altered the Bluetooth stack?

**Comment by Geefbird** [comment]
Yea it is definitely nothing to do with your stuff, because that hasn't changed, I am more or less outsourcing ideas lol, because I have simply run out of things to try short of just disconnecting and reconnecting the lights from the PC, connecting them through the GUI first, and then running them with the HTTP server. That is all that I have been able to get to consistently work so far. 

Tell me more about this bluetooth stack lol, I have had system updates but can't see that being an issue as anyone running windows 11 would have the same update. I was already thinking it would be something bluetooth related.

**Comment by taburineagle** [comment]
What I mean is it's possible a Windows (or whichever OS you're using) changed _something_ that screws with the way Bluetooth worked before the update.  It's possible that's not the case either, there are a lot of ways things can change 😄  It seems weird they'd connect just to disconnect though.

**Comment by adrienJeg** [comment]
Hello! First, thanks for this awesome project. I recently bought a Neewer GL1C, and thought I could control it with this repo. Everything works well when using the GUI, however when I try the http server no command work:

<img width="974" height="437" alt="Image" src="https://github.com/user-attachments/assets/fd114225-3efa-45d0-a117-008395aa2010" />

As you can see it finds my light, but then all commands do nothing. I am sending the commands using Streamerbot, as @Geefbird demonstrated in his video if that helps. I changed the default port of 8080 to 8585 everywhere, including line 4817 in the .py file where 8080 was hardcoded.  The fact that it works well using the GUI is letting me hope the issue is something silly I forgot, but I'm not advanced enough to troubleshoot it myself!

Best regards

**Comment by taburineagle** [comment]
Hi @adrienJeg!  Apologies for the HTTP issues, I will admit that I need to (and have for a while) overhaul the HTTP server part of NeewerLite-Python as it gets confused with Infinity/Infinity-esque style lights (I can't find specifically if the GL1C is Infinity/Inifnity-esque based, but according to the screenshot above, it's set that way.  All of the commands you're sending to the light are correct, so that's definitely an issue with the server sending the wrong bytestream to the light.  I need to check more into what is getting jumbled here!

**Comment by adrienJeg** [comment]
Thanks a lot for your answer @taburineagle , I hope the issue is only superficial then!

**Comment by taburineagle** [comment]
@adrienJeg - It should be - my problem is that I keep getting waylaid by other projects (I usually gave like 20 things going on at once, I'm working on a program to control Hyperdecks, and another one rewriting an old program in Python 😄), so other things fall behind.  I need to do some more testing to see what's different between the GUI's handling of different light types (Infinity/non-Infinity, etc.) and see where the HTTP server is getting confused, because that's the source of most of the "not communicating" issues that have been reported.  I'm closing this bug specifically, but not because it's _fixed_, but because the thread has kind of gotten off the rails, which is more on me than anyone else 😛
